name: Build Qt project for Windows, Ubuntu and Debian aarch64

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x64
            python-version: '3.10'
            container: ''
          - os: ubuntu-latest
            arch: x64
            python-version: '3.10'
            container: ''
          - os: ubuntu-latest
            arch: aarch64
            python-version: '3.10'
            container: debian:latest

    runs-on: ${{ matrix.os }}

    container: ${{ matrix.container != '' && matrix.container || github.job != 'build' && '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.5.0'
          host: ${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
          arch: ${{ matrix.arch }}

      - name: Build project
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            qmake && nmake
          else
            qmake && make
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.arch }}
          path: ./build_output_folder  # Укажите путь к вашим собранным файлам
